{{- range $index, $item := .Values.prometheusRules }}
---
{{ include "nuc-kube-prometheus-stack.renderResource" (dict
  "root" $
  "item" $item
  "kind" "PrometheusRule"
  "defaultApiVersion" $.Values.apiVersions.prometheusRule
  "resourceKey" (printf "prometheusRules[%d]" $index)
  "namespaced" true
) }}
{{- end }}
